[package]
name = "starter-logger"
version = "0.1.0"
edition = "2021"
description = "Beautiful, injectable logger for Rust"
rust-version = "1.83"

[dependencies]

[profile.release]
lto = true
codegen-units = 1
